### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by guga31bb** [nflverse/open-source-football#86]
Clicking on an article here doesn't work https://www.opensourcefootball.com/contributors_list.html

**Comment by tanho63** [comment]
https://github.com/nflverse/open-source-football/blob/master/_site.yml#L5 base URL probably

**Comment by guga31bb** [comment]
Where it should go: https://www.opensourcefootball.com/posts/2020-08-25-defense-and-rest-time-re-visited/

Where it tries to go: https://mrcaseb.github.io/open-source-football/posts/2020-08-25-defense-and-rest-time-re-visited/

**Comment by guga31bb** [comment]
I think it's this line in the thing that builds the table of prior posts https://github.com/nflverse/open-source-football/blob/master/contributors_list.Rmd#L33
