### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by guga31bb** [nflverse/open-source-football#87]
https://www.opensourcefootball.com/contributing.html

> You’ll need R and R Markdown to create the post and the formal structure but the most important thing - your code and it’s output - can be anything you want (please see Ben’s python contributing example)

https://mrcaseb.github.io/open-source-football/posts/2020-08-20-python-contributing-example/

**Comment by mrcaseb** [comment]
We should also update the contributing guide with `usethis::pr_*()` functions.
