### ISSUE TITLE
awesome article on rodgers

### ISSUE THREAD

**Issue by microprediction** [nflverse/open-source-football#88]
"We see that gaining 8 yards (-2 yards to sticks) on 1st and 10 is similar to gaining 10 yards, while gaining 9 yards on 1st down is similar to gaining 12 yards. Therefore a QB who threw for 9 yards on every 1st down would be more valuable than a QB that threw for 11 yards."

We are of like mind (except perhaps choice of language :)

You might like [this](https://github.com/microprediction/firstdown/blob/main/wilmott_paper/44-49_Cotton_PDF5_Jan22%20(2).pdf) although honestly, I thought your article was the more insightful. I will be watching Rodgers with your analysis in mind.

**Comment by tanho63** [comment]
Hiya @microprediction - glad you enjoyed the piece in question! This repository is mostly for technical issues and/or deploying articles to the website. We do have a very active Discord server where most of the discussions around things like this happens: https://discord.gg/UCKxQyuPw5

Closing this for now, please let me know if you have any questions :)
